# Generated by Django 5.0 on 2024-08-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_api', '0003_blacklist_cashback'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTNToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtn_active', models.BooleanField(default=True)),
            ],
        ),
    ]
